spring:
  redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10000000
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/oauth2
      database: oauth2
      host: 127.0.0.1
      port: 27017
    rest:
      base-path: /v1
      enable-enum-translation: true
