spring:
  data:
    rest:
      base-uri: /v1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restdata?autoReconnect=true&useSSL=false
    username: root1
    password: chen789045
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6378
